name: "1.0$(Rev:.r)"

trigger:
  - main

variables:
  CI: "true"

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "14.x"
    displayName: "Install Node.js"
  - task: Npm@1
    inputs:
      command: "ci"
  - task: Npm@1
    inputs:
      command: "custom"
      customCommand: "run-script build"
  - task: Docker@2
    displayName: Login to Docker
    inputs:
      command: login
      containerRegistry: "Docker Hub"
  - task: Docker@2
    displayName: Build and Push Docker Image
    inputs:
      containerRegistry: "Docker Hub"
      repository: jacksondr5/genshin-ui
      command: buildAndPush
      Dockerfile: Dockerfile
      tags: |
        $(Build.BuildNumber)
        latest
